//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeneratingMail.WebActService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClientChk", Namespace="http://schemas.datacontract.org/2004/07/WCFActService")]
    [System.SerializableAttribute()]
    public partial class ClientChk : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClGudField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClientIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GuIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResultField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClGud {
            get {
                return this.ClGudField;
            }
            set {
                if ((object.ReferenceEquals(this.ClGudField, value) != true)) {
                    this.ClGudField = value;
                    this.RaisePropertyChanged("ClGud");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClientId {
            get {
                return this.ClientIdField;
            }
            set {
                if ((object.ReferenceEquals(this.ClientIdField, value) != true)) {
                    this.ClientIdField = value;
                    this.RaisePropertyChanged("ClientId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GuId {
            get {
                return this.GuIdField;
            }
            set {
                if ((object.ReferenceEquals(this.GuIdField, value) != true)) {
                    this.GuIdField = value;
                    this.RaisePropertyChanged("GuId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Result {
            get {
                return this.ResultField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultField, value) != true)) {
                    this.ResultField = value;
                    this.RaisePropertyChanged("Result");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TransactMsg", Namespace="http://schemas.datacontract.org/2004/07/WCFActService")]
    [System.SerializableAttribute()]
    public partial class TransactMsg : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TransactStringField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TransactString {
            get {
                return this.TransactStringField;
            }
            set {
                if ((object.ReferenceEquals(this.TransactStringField, value) != true)) {
                    this.TransactStringField = value;
                    this.RaisePropertyChanged("TransactString");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WebActService.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CliDet", ReplyAction="http://tempuri.org/IService1/CliDetResponse")]
        GeneratingMail.WebActService.ClientChk CliDet(GeneratingMail.WebActService.ClientChk Cli, string Bhadram);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SynchActMasterData", ReplyAction="http://tempuri.org/IService1/SynchActMasterDataResponse")]
        System.Collections.Generic.List<GeneratingMail.WebActService.TransactMsg> SynchActMasterData(GeneratingMail.WebActService.ClientChk Cli);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ActDataDownLoaded", ReplyAction="http://tempuri.org/IService1/ActDataDownLoadedResponse")]
        string ActDataDownLoaded(GeneratingMail.WebActService.ClientChk Cli);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : GeneratingMail.WebActService.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<GeneratingMail.WebActService.IService1>, GeneratingMail.WebActService.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public GeneratingMail.WebActService.ClientChk CliDet(GeneratingMail.WebActService.ClientChk Cli, string Bhadram) {
            return base.Channel.CliDet(Cli, Bhadram);
        }
        
        public System.Collections.Generic.List<GeneratingMail.WebActService.TransactMsg> SynchActMasterData(GeneratingMail.WebActService.ClientChk Cli) {
            return base.Channel.SynchActMasterData(Cli);
        }
        
        public string ActDataDownLoaded(GeneratingMail.WebActService.ClientChk Cli) {
            return base.Channel.ActDataDownLoaded(Cli);
        }
    }
}
